export enum LienEntrePersonnages {
  FrereSoeur = 'FRERE_SOEUR',
  Parent = 'PARENT',
  Enfant = 'ENFANT',
  GrandParent = 'GRAND_PARENT',
  PetitEnfant = 'PETIT_ENFANT',
  Cousin = 'COUSIN',
  Ami = 'AMI',
  Amoureux = 'AMOUREUX',
  MeilleurAmi = 'MEILLEUR_AMI',
  Inconnu = 'INCONNU',
  Voisin = 'VOISIN',
  Camarade = 'CAMARADE',
  Animal = 'ANIMAL',
}
